[package]
name = "mail-utilities-wizard"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'

[dependencies]
anyhow = "1.0.86"

config = { version = "0.14.0", features = ["yaml"] }

axum = "0.7.5"

log = "0.4.22"
log4rs = "1.3.0"