port: 8080

log-level: debug

locations:
  - name: 'Saint Petersburg, Nevsky Street, 123'
    counters:
    - name: 'Electricity'
      account-id: '85678463456'
      email: 'electricity@company1.com'

    - name: 'Water'
      account-id: '568346545734'
      email: 'water@company2.com'
      template: 'custom-template.txt'
      signature: 'Boris Britva'

defaults:
  template: 'example.txt'
  signature: 'Evgeny Lebedev'

page:
  title: 'Mail Utilities Wizard'
  header: 'Send utilities data'
  select-location-label: 'Select location:'
  select-location-dropdown: '- Select -'
  select-counter-label: 'Select counter:'
  select-counter-dropdown: '- Select -'
  account-id-label: 'Your account id:'
  account-id-placeholder: '1234567'
  email-label: 'Data will be sent to e-mail:'
  counter-value-label: 'Counter value:'
  counter-default-value: '0'
  send-confirm-msg: 'Do you want to continue?'
  send-confirm-yes: 'Yes'
  send-confirm-no: 'No'
  send-button: 'Send'
  send-more-button: 'Send more'
  app-error-msg: 'Application error'
  sending-msg: 'Sending..'
  send-success-msg: 'Counter value has been sent'
  send-error-msg: 'Unable to send counter data, contact john@company.com'

mail:
  from: eugene@mail.com
  host: localhost
  port: 1025
  username: change-me
  password: change-me