port: 8080

log-level: debug

locations:
  - name: 'Saint Petersburg, Nevsky Street, 123'
    counters:
    - name: 'Electricity'
      account-id: '85678463456'
      email: 'electricity@company1.com'

    - name: 'Water'
      account-id: '568346545734'
      email: 'water@company2.com'
      email-copy: 'relative@mail.com'
      template: 'custom-template.txt'
      signature: 'Boris Britva'

defaults:
  email-copy: 'default@mail.com'
  template: 'example.txt'
  signature: 'Evgeny Lebedev'

page:
  locale: 'en'
  title: 'Mail Utilities Wizard'
  header: 'Send utilities data'
  select-location-label: 'Select location:'
  select-location-dropdown: '- Select -'
  select-counter-label: 'Select counter:'
  select-counter-dropdown: '- Select -'
  account-id-label: 'Your account id:'
  account-id-hint: 'Unique for each counter'
  email-label: 'Data will be sent to e-mail:'
  period-label: 'Period:'
  counter-value-label: 'Counter value:'
  mail-template-title: 'Letter'
  mail-template-to-label: 'To:'
  mail-template-body-label: 'Body:'
  mail-template-close-button: 'Close'

  send-confirm-msg: 'Do you want to continue?'
  send-button: 'Send'
  send-more-button: 'Send more'
  show-letter-button: 'Show the letter'
  app-error-msg: 'Application error'
  sending-msg: 'Sending..'
  send-success-msg: 'Counter value has been sent'
  send-error-msg: 'Unable to send counter data, contact john@company.com'

mail:
  from: eugene@mail.com
  host: localhost
  port: 1025
  username: change-me
  password: change-me