bind: '127.0.0.1:8080'

db-cnn: 'sqlite://app.db?mode=rwc'

log-level: debug

auth:
  enabled: true
  password: 'h246346rGw3g545'
  secret: '23FS0932fdfSD'

locations:
  - name: 'Saint Petersburg, Nevsky Street, 123'
    counters:
    - name: 'Water'
      account-id: '568346545734'
      email: 'water@company2.com'
      email-copy: 'relative@mail.com'
      mail-subject-template: 'Counter {{ counter_name }} data for {{ month }} 2'
      mail-body-template-file: 'custom-template.txt'
      signature: 'Boris Britva'

    - name: 'Electricity'
      account-id: '85678463456'
      url: 'https://metrics.company.com/population/send-and-pay/?from=main-menu'
      manual: 'Electricity provider requires to send counter data via web site. Use account-id to log-in.'

defaults:
  email-copy: 'default@mail.com'
  mail-subject-template: 'Counter {{ counter_name }} data for {{ month }}'
  mail-body-template-file: 'example.txt'
  signature: 'Evgeny Lebedev'

page:
  locale: 'en'
  title: 'Mail Utilities Wizard'
  header: 'Send utilities data'
  select-location-label: 'Select location:'
  select-location-dropdown: '- Select -'
  select-counter-label: 'Select counter:'
  select-counter-dropdown: '- Select -'
  account-id-label: 'Your account id:'
  account-id-hint: 'Unique for each counter'
  email-label: 'Data will be sent to e-mail:'
  period-label: 'Period:'
  counter-value-label: 'Counter value:'
  mail-template-title: 'Letter'
  mail-template-to-label: 'To:'
  mail-template-subject-label: 'Subject:'
  mail-template-body-label: 'Body:'
  mail-template-close-button: 'Close'

  send-confirm-msg: 'Do you want to continue?'
  send-button: 'Send'
  send-more-button: 'Send more'
  show-letter-button: 'Show the letter'
  app-error-msg: 'Application error'
  sending-msg: 'Sending..'
  send-success-msg: 'Counter value has been sent'
  send-error-msg: 'Unable to send counter data, contact john@company.com'

mail:
  from: eugene@mail.com
  host: localhost
  port: 1025
  username: change-me
  password: change-me